### PR TITLE
Camera position, lookAt properties

### PR DESCRIPTION
**Pull request by CrosRoad95**
Changes set accessor to internal to force people to use "SetMatrix" method.
Right now it is a bit confusing what to use.

### CODE REVIEW

**Review by NanoBob — CHANGES_REQUESTED** [review]
Shouldn't this be private instead of internal?

**Comment by CrosRoad95** [comment]
> Shouldn't this be private instead of internal?

no, because it is set in CameraSyncPacketHandler

**Comment by NanoBob** [comment]
> > Shouldn't this be private instead of internal?
> 
> no, because it is set in CameraSyncPacketHandler

In that case it should be public.
Keep in mind it should be possible for a consumer of the Slipe Server library to be able to create their own packet handlers as well. (If they aren't satisfied with our defaults).

**Comment by NanoBob** [comment]
What you could do to make this more intuitive is have the setters of the `LookAt` and `Position` properties send the packet too.
Then in the actual `SetMatrix` method use the private members instead of the properties to bypass the setter (in order to make sure the packet doesn't get sent twice)

**Pull request closed without merging**
